name: start_note
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  audioplayers:
  bloc:
  path_provider:
  just_audio:
  intl:
  file_picker:
  flutter_bloc:
  hydrated_bloc: 
  sqflite: 
  draggable_widget: 
  equatable: 
  logging_appenders: 
  flutter_slidable: 
  logging: 
  holding_gesture: 
  shared_preferences:
  uuid:

   
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/launcher.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
